export enum RouteType {
    LoginReq = "loginReq",
    LoginRes = "loginRes",
    MakeAccountReq = "makeAccReq",
    MakeAccountRes = "makeAccRes",
    AccountListReq = "accListReq",
    AccountListRes = "accListRes",
    LoadKeysReq = "loadkeyReq",
    LoadKeysRes = "loadkeyRes",
    SessionCheckReq = "sCheckReq",
    SessionCheckRes = "sCheckRes",
    SessionFailNoti = "sFail",
    BlockInfoReq = "bInfoReq",
    BlockInfoRes = "bInfoRes",
    BlockListReq = "bListReq",
    BlockListRes = "bListRes",
    AccountInfoReq = "accInfoReq",
    AccountInfoRes = "accInfoRes",
    GetBlockReq = "bStatReq",
    GetBlockRes = "bStatRes",
    GetPeersReq = "peersReq",
    GetPeersRes = "peersRes",
    GetLogsReq = "logsReq",
    GetLogsRes = "logsRes",
}