export enum RouteType {
    LoginReq = "loginReq",
    LoginRes = "loginRes",
    MakeAccountReq = "makeAccReq",
    MakeAccountRes = "makeAccRes",
    AccountListReq = "accListReq",
    AccountListRes = "accListRes",
    LoadKeysReq = "loadkeyReq",
    LoadKeysRes = "loadkeyRes",
    SessionCheckReq = "sCheckReq",
    SessionCheckRes = "sCheckRes",
    SessionFailNoti = "sFail",
    AccountInfoReq = "accInfoReq",
    AccountInfoRes = "accInfoRes",
    GetLogsReq = "logsReq",
    GetLogsRes = "logsRes",
    PeerStart = "peerStart",
    PeerReq = "peerReq",
    PeerRes = "peerRes",
    PeerOnReg = "peerOn",
    PeerOnceReg = "peerOnce",
    DbGetReq = "dbgReq",
    DbPutReq = "dbpReq",
    DbDelReq = "dbDReq",
    DbIterReq = "dbiReq",
    DbIterChunk = "dbiChunk",
    DbRes = "dbRes",
}